name: voice_reader
description: A native voice reader app.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_tts: ^3.8.3
  file_picker: ^6.1.1
  shared_preferences: ^2.2.1
  syncfusion_flutter_pdf: ^24.1.41
  excel: ^4.0.0

dependency_overrides:
  flutter_plugin_android_lifecycle: 2.0.23

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
